branches:
  # all branches
  only:
  - gh-pages
  - /.*/

language: python

python:
  - "3.6"

services:
  - docker

install:
  # Build/test dependencies
  - pip install --no-cache-dir -r requirements/prod.txt
  - pip install coveralls
script:
  - echo $TRAVIS_BRANCH;
  # Run django tests.  (Note: For django settings, use a travis env variable)
  #
  - python manage.py test

after_success:
  #
  # Build images and push to dockerhub
  #
  - echo $TRAVIS_BRANCH;
  #- if [ "$TRAVIS_BRANCH" == "master" ]; then
  - if [ "$TRAVIS_BRANCH" == "26-tags" ]; then
    docker build -t tworavens/psi-web:master -f Dockerfile-web .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push tworavens/psi-web:master;
    fi
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
    docker build -t tworavens/psi-web:latest -f Dockerfile-web .;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push tworavens/psi-web:latest;
    fi
  #
  # send report to coveralls
  #
  - coveralls
