version: '3'

services:
  db:
    image: django
  web:
    build:
      context: ./
      dockerfile: Dockerfile-django
    environment:
      - ROOK_SERVER=http://rook-service:8000
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/psi_volume
    ports:
      - "8080:8080"
    depends_on:
      - db
  rook-service:
    build:
      context: ./
      dockerfile: Dockerfile-r-service
    ports:
      - "8000:8000"
    volumes:
      - ./psi_volume:/psi_volume
