version: '3'

services:
  #db:
  #  image: django
  web:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile-web
    environment:
      - ROOK_SERVER=http://rook-service:8000/custom/
    command: python manage.py runserver 0.0.0.0:8080
    #command: psi_start.sh
    volumes:
      - .:/psi_volume
    ports:
      - "8080:8080"
    depends_on:
      - rook-service
  rook-service:
    stdin_open: true
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile-r-service
    environment:
      - IS_PRODUCTION_MODE=no
    ports:
      - "8000:8000"
    volumes:
      - .:/psi_volume
